apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dummy-server
  namespace: dummy-server
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: dummy.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dummy-server
                port:
                  number: 80
