apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-server
  namespace: argocd
spec:
  project: default
  source:
    # TODO: 본 저장소를 다른 저장소/포크로 바꿀 경우 repoURL만 수정한다.
    repoURL: https://github.com/workingdad365/gitops_test.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: dummy-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
