apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/workingdad365/gitops_test.git
    targetRevision: main
    path: helm/dummy-server
    helm:
      releaseName: dummy-server
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dummy-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
